version: '3.8'

services:
  vqa-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vqa-container
    ports:
      - "3000:3000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
